# LECTURA Y ESCRITURA DE FICHEROS EN PANDAS
***

En este notebook se explicarán los principales métodos de lectura y escritura de archivos excel, csv, txt y algunas funciones utiles de la la libreria pandas en python, ademas se realizará una exploración de los datos aplicando algunas funciones importantes de pandas.

[1. Lectura de archivos excel, csv, txt, html](#1.-Lectura-de-archivos-excel,-csv,-txt,-html)<br>
[2. Funciones básicas de lectura de ficheros](#2.-Funciones-básicas-de-lectura-de-ficheros)<br>
[3. Funciones básicas de almacenamiento](#3.-Funciones-básicas-de-almacenamiento)<br>
[4. Explorando nuestro DataFrame](#4.-Explorando-nuestro-DataFrame)<br>

In [2]:
# importar libreria
import pandas as pd
import xlrd
pd.__version__

'2.2.3'

## <font color=#33A5FF>****1. Lectura de archivos excel, csv, txt, html****<tfont>

### Descripción del las columnas del DataFrame

Para leer ficheros de excel puedes instalar en el anaconda Prom: **pip install xlrd**, seguido de ello puedes cargar el fichero titanic el cual contiene la siguiente información:

* **Id_Pasajero:** Id de cada pasajero.

* **Survived:** esta característica tiene valor 0 y 1. 0 para no sobrevivido y 1 para sobrevivido.

* **Clase:** Hay 3 clases: Clase 1, Clase 2 y Clase 3.

* **Nombre:** Nombre del pasajero.

* **Sexo:** Género del pasajero.

* **Edad:** Edad del pasajero.

* **Familiares:** numero de familiares del pasajero.

* **Ticket:** Número de ticket del pasajero.

* **Tarifa:** Indicando la tarifa.

* **Cabina:** La cabina del pasajero.

* **Embarcado:** La categoría embarcada.

In [58]:
# Espeficicar la ruta o dirección de los archivos

Leer datos archivos excel con extensión **--->** .xls, .xlsx

In [3]:
# Leer datos excel con ruta, en caso de que el archivo se encuentre en una ruta diferente 
pd.read_excel('titanic.xlsx')

,1,0,3,"Braund, Mr. Owen Harris",Masculino,22,0.1,A/5 21171,7.25,Unnamed: 9,S
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
1,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
3,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
4,6,0,3,"Moran, Mr. James",Masculino,NaN,0,330877,8.46,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
886,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
887,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
888,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
889,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

In [60]:
# Leer datos excel si el archivo se encuentra dentro de la misma carpeta del notebook
pd.read_csv('titanic.csv',sep=';')

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

Leer datos archivos excel con extensión ---> **.csv**

In [61]:
# Leer archivos .csv

Leer datos archivos excel con extensión ---> **.txt**

In [62]:
# Leer archivos .txt
pd.read_csv('titanic.txt', sep=';')

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

Leer datos de archivos html --> **.html**

In [ ]:
# Leer archivo titanic siempre debes poner [0] para saber que tabla poner

df = pd.read_html("titanic.html")

In [64]:
df[0]

,Unnamed: 0,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

In [5]:
# leer archivo desde pagina web
df1 = pd.read_html("https://es.m.wikipedia.org/wiki/Luisiana")
df1[1]
#es por la red que lo bloquea

HTTPError: HTTP Error 403: Forbidden

Leer datos de archivos Json --> **.Json**

## <font color=#33A5FF>****2. Funciones básicas de lectura de ficheros****<tfont>

**index_col** = Cambiar el índice

In [ ]:
# Opción index_col
pd.read_excel('titanic.xlsx', index_col=0)

**nrows** = utilizar las n primeras filas

In [ ]:
# Opción nrows (para traer las filas  quen quiero)
pd.read_excel('titanic.xlsx', nrows=10)

,Id_Pasajero,Survived,Clase,Nombre,Sexo,Edad,Familiares,Tiquete,Tarifa,Cabina,Embarcado
0,1,0,3,"Braund, Mr. Owen Harris",Masculino,22.0,0,A/5 21171,7.25,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
4,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
5,6,0,3,"Moran, Mr. James",Masculino,NaN,0,330877,8.46,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",Masculino,54.0,0,17463,51.86,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",Masculino,2.0,1,349909,21.08,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",Femenino,27.0,2,347742,11.13,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",Femenino,14.0,0,237736,30.07,NaN,C

**usecols**: Utilizar columnas específicas

In [ ]:
# Opción usecols ( para solo traer las columnas que quiere mostrar)
pd.read_excel('titanic.xlsx', usecols=['Survived',	'Clase',	'Nombre',	'Sexo',	'Edad'])

,Survived,Clase,Nombre,Sexo,Edad
0,0,3,"Braund, Mr. Owen Harris",Masculino,22.0
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0
2,1,3,"Heikkinen, Miss. Laina",Femenino,26.0
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0
4,0,3,"Allen, Mr. William Henry",Masculino,35.0
...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",Masculino,27.0
887,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN
889,1,1,"Behr, Mr. Karl Howell",Masculino,26.0
890,0,3,"Dooley, Mr. Patrick",Masculino,32.0

**skiprows**: saltarse filas de abajo hacia arriba

In [ ]:
# Opción skiprows
#sirve para salltarte filas para ver

**sheet_name**: Seleccionar las pestañas del libro excel

In [6]:
# Opción sheet_name (para leer un hoja en especifico de excel)
pd.read_excel('titanic.xlsx', sheet_name=0)

,1,0,3,"Braund, Mr. Owen Harris",Masculino,22,0.1,A/5 21171,7.25,Unnamed: 9,S
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
1,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
3,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
4,6,0,3,"Moran, Mr. James",Masculino,NaN,0,330877,8.46,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
886,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
887,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
888,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
889,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

**header**: Se utiliza cuando las columnas no tienen encabezado

In [ ]:
# Opción header ( para COLCAR ENCABEZAMOS A UNA TABLA)
pd.read_excel('titanic.xlsx', header=None , names= ['Id_Pasajero',	'Survived'	,'Clase'	,'Nombre'	,'Sexo',	'Edad'	,'Familiares'	,'Tiquete',	'Tarifa',	'Cabina',	'Embarcado'], sheet_name="Pasajeros_1")

In [86]:
# Opción heater asignando nombre de las columnas

titanic = pd.read_excel('titanic.xlsx')
titanic

,1,0,3,"Braund, Mr. Owen Harris",Masculino,22,0.1,A/5 21171,7.25,Unnamed: 9,S
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Femenino,38.0,0,PC 17599,71.28,C85,C
1,3,1,3,"Heikkinen, Miss. Laina",Femenino,26.0,0,STON/O2. 3101282,7.93,NaN,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Femenino,35.0,0,113803,53.10,C123,S
3,5,0,3,"Allen, Mr. William Henry",Masculino,35.0,0,373450,8.05,NaN,S
4,6,0,3,"Moran, Mr. James",Masculino,NaN,0,330877,8.46,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...
885,887,0,2,"Montvila, Rev. Juozas",Masculino,27.0,0,211536,13.00,NaN,S
886,888,1,1,"Graham, Miss. Margaret Edith",Femenino,19.0,0,112053,30.00,B42,S
887,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Femenino,NaN,2,W./C. 6607,23.45,NaN,S
888,890,1,1,"Behr, Mr. Karl Howell",Masculino,26.0,0,111369,30.00,C148,C
889,891,0,3,"Dooley, Mr. Patrick",Masculino,32.0,0,370376,7.75,NaN,Q

**parse_dates**: Para manejar series temporales

## <font color=#33A5FF>****3. Funciones básicas de almacenamiento****<tfont>

In [9]:
# Ruta de la carpeta donde quiero guardar mis archivos exportados
titanic = pd.read_excel('titanic.xlsx', header=None, names=[
        'Id_Pasajero','Survived','Clase','Nombre','Sexo','Edad',
        'Familiares','Tiquete','Tarifa','Cabina','Embarcado'
    ],
    sheet_name="Pasajeros_1"
)
# Exportar archivo formato excel 
titanic.to_excel('titanic_limpio.xlsx', index=False)

In [ ]:
# Exportar archivo formato excel 
titanic.to_excel('titanic_limpio.xlsx', index=False)

In [ ]:
# Exportar archivo formato excel sin índices

In [10]:
# Exportar archivo formato .csv 
titanic.to_csv('titanic_nuevo.csv')

In [11]:
# Exportar archivo formato .txt 
titanic.to_csv('titanic_nuevo.txt')

In [12]:
# Exportar archivo formato .html 
titanic.to_html('titanic_nuevo.html')

## <font color=#33A5FF>****4. Explorando nuestro DataFrame****<tfont>

In [ ]:
# Explorar datos opción dtypes= para ver el tipo de archivo. Dataframe
type(titanic)

In [ ]:
# Explorar datos opción shape 
titanic.shape

In [ ]:
# Ver primeras filas datos opción head() ---> muestra las priemras filas que qieras
titanic.head(20)

In [ ]:
# Ver últimas filas opción tail() --> muestra las ultimas filas que qieras
titanic.tail(10)

In [ ]:
# Ordenar datos por columnas