In [17]:
import pandas as pd
import os
os.getcwd()

'c:\\Users\\Administrador_BI\\AppData\\Local\\Programs\\Microsoft VS Code'

In [21]:
os.chdir(r'C:\Users\Administrador_BI\Desktop\python_prueba')

In [25]:
df = pd.read_excel('win.xlsx', usecols=["LIST_ID","CAMPAÑA","TIPIFICACION","DNI","AGENTE"])
df

,LIST_ID,CAMPAÑA,TIPIFICACION,DNI,AGENTE
0,408,WINOUT,AUTORIZA- SIN COBERTURA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
1,404,WINOUT,AUTORIZA - AGENDADO,46691128,HAUDE DAVID CALDERON SAN MIGUEL
2,404,WINOUT,AUTORIZA- SIN COBERTURA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
3,408,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
4,404,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
...,...,...,...,...,...
157,404,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
158,407,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
159,407,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
160,407,WINOUT,AUTORIZA - VOLVER A LLAMAR,46691128,HAUDE DAVID CALDERON SAN MIGUEL
161,404,WINOUT,AUTORIZA - VOLVER A LLAMAR,46691128,HAUDE DAVID CALDERON SAN MIGUEL

In [27]:
df

,LIST_ID,CAMPAÑA,TIPIFICACION,DNI,AGENTE
0,408,WINOUT,AUTORIZA- SIN COBERTURA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
1,404,WINOUT,AUTORIZA - AGENDADO,46691128,HAUDE DAVID CALDERON SAN MIGUEL
2,404,WINOUT,AUTORIZA- SIN COBERTURA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
3,408,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
4,404,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
...,...,...,...,...,...
157,404,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
158,407,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
159,407,WINOUT,AUTORIZA- CORTA LLAMADA,46691128,HAUDE DAVID CALDERON SAN MIGUEL
160,407,WINOUT,AUTORIZA - VOLVER A LLAMAR,46691128,HAUDE DAVID CALDERON SAN MIGUEL
161,404,WINOUT,AUTORIZA - VOLVER A LLAMAR,46691128,HAUDE DAVID CALDERON SAN MIGUEL

In [28]:
pd.read_excel('win.xlsx', sheet_name=2)

,LIST_ID,CAMPAÑA,FECHA,TMO,STATUS,TIPIFICACION,TELEFONO,DNI,AGENTE,TERMINO_LLAMADA,...,TIPIFICACIONES POR AGENTES,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35
0,396,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,914922217,74536535,SANDRA PAMELA CONDEZO SOTO,ABANDON,...,TIPOLOGÌA,Sospechosa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,278,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,937647656,74075275,JOAQUIN ANTONIO CALLE MENDOZA,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,396,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,992625371,10015709,YSABELINA LOA RAMOS,NONE,...,Cuenta de FECHA,Etiquetas de columna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,396,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,950173921,74417924,ANGEL LEONEL GUIDINO HERRERA,AGENTE,...,Etiquetas de fila,AUTORIZA - AGENDADO,AUTORIZA - VENTA,AUTORIZA- CONF CON SU OPERADOR,AUTORIZA- CORTA LLAMADA,FUERA DE SERVICIO,LLAMADA MUDA,NO AUTORIZA COMUNICACION,NO CONTESTA,Total general
4,404,WINOUT,2025-10-01,00:00:00,1CEF05,AUTORIZA- NO DESEA-PRODUCTO,933024736,72322895,DEYANIRA AYLIN ESPINOZA CHECA,AGENTE,...,AGUILAR MOLINA JOSEPH MICHAEL,20,4,NaN,6,NaN,NaN,335,1,366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7829,408,WINOUT,2025-10-01,NaN,INCALL,NaN,968092940,60683672,CIELO DEL PILAR PANDURO FLORES,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7830,408,WINOUT,2025-10-01,NaN,INCALL,NaN,953693430,76602643,CIOMARA FLOR VILLANO MOLLE,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7831,998,WINOUT,2025-10-01,NaN,INCALL,NaN,994037592,73150537,PACHECO YUPANQUI TANIA MILAGROS,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7832,408,WINOUT,2025-10-01,NaN,INCALL,NaN,998481147,74802241,ALEXSANDRA VICTORIA CHINCHON RAZON,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7833,372,WINOUT,2025-10-01,NaN,INCALL,NaN,971487827,73285107,JEAN PAUL SALAMANCA TORRES,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df['LIST_ID'].unique().tolist()

[408, 404, 407, 504, 395, 396, 387, 998, 239, 390, 372, 503]

In [38]:
df['LIST_ID'].nunique()

12

In [40]:
df = pd.read_excel('win.xlsx').head()

In [ ]:
df[['STATUS']]

   STATUS                           AGENTE
0  2CNE03  HAUDE DAVID CALDERON SAN MIGUEL
1  1CEF02  HAUDE DAVID CALDERON SAN MIGUEL
2  2CNE03  HAUDE DAVID CALDERON SAN MIGUEL
3  2CNE01  HAUDE DAVID CALDERON SAN MIGUEL
4  2CNE01  HAUDE DAVID CALDERON SAN MIGUEL

In [45]:
df['STATUS'] = '1CEF01'
df

,LIST_ID,CAMPAÑA,FECHA,TMO,STATUS,TIPIFICACION,TELEFONO,DNI,AGENTE,TERMINO_LLAMADA,TIPO_LLAMADA,GESTION,AGENDADO,VENTA,VOLVER A LLAMAR,CORTA LLAMADA,TIPOLOGÌA
0,408,WINOUT,2025-10-01,00:20:38,1CEF01,AUTORIZA- SIN COBERTURA,968050812,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Correcta
1,404,WINOUT,2025-10-01,00:12:44,1CEF01,AUTORIZA - AGENDADO,950168047,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa
2,404,WINOUT,2025-10-01,00:08:35,1CEF01,AUTORIZA- SIN COBERTURA,945853311,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Correcta
3,408,WINOUT,2025-10-01,00:04:53,1CEF01,AUTORIZA- CORTA LLAMADA,972819271,46691128,HAUDE DAVID CALDERON SAN MIGUEL,CLIENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa
4,404,WINOUT,2025-10-01,00:03:57,1CEF01,AUTORIZA- CORTA LLAMADA,955258851,46691128,HAUDE DAVID CALDERON SAN MIGUEL,AGENTE,AUTO,OPERACIONES,0,0,0,0,Sospechosa

In [ ]:
df = pd.read_excel('win.xlsx', sheet_name=2)

,LIST_ID,CAMPAÑA,FECHA,TMO,STATUS,TIPIFICACION,TELEFONO,DNI,AGENTE,TERMINO_LLAMADA,...,TIPIFICACIONES POR AGENTES,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35
0,396,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,914922217,74536535,SANDRA PAMELA CONDEZO SOTO,ABANDON,...,TIPOLOGÌA,Sospechosa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,278,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,937647656,74075275,JOAQUIN ANTONIO CALLE MENDOZA,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,396,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,992625371,10015709,YSABELINA LOA RAMOS,NONE,...,Cuenta de FECHA,Etiquetas de columna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,396,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,950173921,74417924,ANGEL LEONEL GUIDINO HERRERA,AGENTE,...,Etiquetas de fila,AUTORIZA - AGENDADO,AUTORIZA - VENTA,AUTORIZA- CONF CON SU OPERADOR,AUTORIZA- CORTA LLAMADA,FUERA DE SERVICIO,LLAMADA MUDA,NO AUTORIZA COMUNICACION,NO CONTESTA,Total general
4,404,WINOUT,2025-10-01,00:00:00,1CEF05,AUTORIZA- NO DESEA-PRODUCTO,933024736,72322895,DEYANIRA AYLIN ESPINOZA CHECA,AGENTE,...,AGUILAR MOLINA JOSEPH MICHAEL,20,4,NaN,6,NaN,NaN,335,1,366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7829,408,WINOUT,2025-10-01,NaN,INCALL,NaN,968092940,60683672,CIELO DEL PILAR PANDURO FLORES,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7830,408,WINOUT,2025-10-01,NaN,INCALL,NaN,953693430,76602643,CIOMARA FLOR VILLANO MOLLE,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7831,998,WINOUT,2025-10-01,NaN,INCALL,NaN,994037592,73150537,PACHECO YUPANQUI TANIA MILAGROS,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7832,408,WINOUT,2025-10-01,NaN,INCALL,NaN,998481147,74802241,ALEXSANDRA VICTORIA CHINCHON RAZON,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7833,372,WINOUT,2025-10-01,NaN,INCALL,NaN,971487827,73285107,JEAN PAUL SALAMANCA TORRES,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df[df['STATUS'] == '1CEF01']

<bound method DataFrame.nunique of      LIST_ID CAMPAÑA      FECHA       TMO  STATUS      TIPIFICACION  \
102      998  WINOUT 2025-10-01  00:01:13  1CEF01  AUTORIZA - VENTA
103      404  WINOUT 2025-10-01  00:01:43  1CEF01  AUTORIZA - VENTA
104      404  WINOUT 2025-10-01  00:02:05  1CEF01  AUTORIZA - VENTA
105      404  WINOUT 2025-10-01  00:02:19  1CEF01  AUTORIZA - VENTA
106      271  WINOUT 2025-10-01  00:07:35  1CEF01  AUTORIZA - VENTA
107      278  WINOUT 2025-10-01  00:08:25  1CEF01  AUTORIZA - VENTA
108      407  WINOUT 2025-10-01  00:09:18  1CEF01  AUTORIZA - VENTA
109      407  WINOUT 2025-10-01  00:11:44  1CEF01  AUTORIZA - VENTA
110      408  WINOUT 2025-10-01  00:11:47  1CEF01  AUTORIZA - VENTA
111      503  WINOUT 2025-10-01  00:12:36  1CEF01  AUTORIZA - VENTA
112      227  WINOUT 2025-10-01  00:13:02  1CEF01  AUTORIZA - VENTA
113      387  WINOUT 2025-10-01  00:13:44  1CEF01  AUTORIZA - VENTA
114      404  WINOUT 2025-10-01  00:14:52  1CEF01  AUTORIZA - VENTA
115      404  WINOUT 2025-10-01  00:16:01  1CEF01  AUTORIZA - VENTA
116      408  WINOUT 2025-10-01  00:16:50  1CEF01  AUTORIZA - VENTA
117      507  WINOUT 2025-10-01  00:16:56  1CEF01  AUTORIZA - VENTA
118      408  WINOUT 2025-10-01  00:17:34  1CEF01  AUTORIZA - VENTA
119      404  WINOUT 2025-10-01  00:21:05  1CEF01  AUTORIZA - VENTA
120      388  WINOUT 2025-10-01  00:21:55  1CEF01  AUTORIZA - VENTA
121      404  WINOUT 2025-10-01  00:23:09  1CEF01  AUTORIZA - VENTA
122      502  WINOUT 2025-10-01  00:24:03  1CEF01  AUTORIZA - VENTA
123      404  WINOUT 2025-10-01  00:25:21  1CEF01  AUTORIZA - VENTA
124      404  WINOUT 2025-10-01  00:26:35  1CEF01  AUTORIZA - VENTA
125      271  WINOUT 2025-10-01  00:27:01  1CEF01  AUTORIZA - VENTA
126      407  WINOUT 2025-10-01  00:29:03  1CEF01  AUTORIZA - VENTA
127      388  WINOUT 2025-10-01  00:30:00  1CEF01  AUTORIZA - VENTA
128      407  WINOUT 2025-10-01  00:36:21  1CEF01  AUTORIZA - VENTA
129      407  WINOUT 2025-10-01  00:36:51  1CEF01  AUTORIZA - VENTA
130      502  WINOUT 2025-10-01  00:00:01  1CEF01  AUTORIZA - VENTA
131      404  WINOUT 2025-10-01  00:00:02  1CEF01  AUTORIZA - VENTA
132      998  WINOUT 2025-10-01  00:00:04  1CEF01  AUTORIZA - VENTA
133      251  WINOUT 2025-10-01  00:00:24  1CEF01  AUTORIZA - VENTA

      TELEFONO       DNI                              AGENTE TERMINO_LLAMADA  \
102  920162433  46691128     HAUDE DAVID CALDERON SAN MIGUEL         CLIENTE
103  931099399  75200837       AGUILAR MOLINA JOSEPH MICHAEL          AGENTE
104  931099399  75200837       AGUILAR MOLINA JOSEPH MICHAEL          AGENTE
105  960370449  73003562            DARIO DARWIN MAMANI JARA          AGENTE
106  950279789  74973677           JEYSON PAUL ESPINOZA DIAZ         CLIENTE
107  992290376  70494580    NICOLE GERALDINE YGUIA ARANCIBIA          AGENTE
108  929697667  73285107          JEAN PAUL SALAMANCA TORRES         CLIENTE
109  987084010  72322895       DEYANIRA AYLIN ESPINOZA CHECA         CLIENTE
110  955554569  73150537     PACHECO YUPANQUI TANIA MILAGROS         CLIENTE
111  900217807   3411835  EDURYELIS NOHEMI SANTAMARA NOGUERA          AGENTE
112  984141683  73150537     PACHECO YUPANQUI TANIA MILAGROS          AGENTE
113  984841023  46691128     HAUDE DAVID CALDERON SAN MIGUEL          AGENTE
114  931099399  75200837       AGUILAR MOLINA JOSEPH MICHAEL          AGENTE
115  990657326  73081606        MANUEL ALBERTO ARIAS VENEGAS          AGENTE
116  934871467  73081606        MANUEL ALBERTO ARIAS VENEGAS          AGENTE
117  920247549  73150537     PACHECO YUPANQUI TANIA MILAGROS          AGENTE
118  913464156  74536535          SANDRA PAMELA CONDEZO SOTO          AGENTE
119  984267732   3411835  EDURYELIS NOHEMI SANTAMARA NOGUERA         CLIENTE
120  969048470  75663085            ALEXIS ARTURO SILVA RUIZ          AGENTE
121  981778540  74858894      YESSENIA MILAGROS PULACHE ZUTA         CLIENTE
122  933710754  61296135       RIVERA GARRIDO JASURI JHANETH          AGENTE
123  956751047  60851481        RICARDO OMAR MERCADO HEREDIA         CLIENTE
124  960370449  73003562            DARIO DARWIN MAMANI JARA         CLIENTE
125  950279789  74973677           JEYSON PAUL ESPINOZA DIAZ         CLIENTE
126  957277411  10015709                 YSABELINA LOA RAMOS          AGENTE
127  928476568  60683672      CIELO DEL PILAR PANDURO FLORES          AGENTE
128  937520966  60768353      JOSEPH ISMAEL LA ROSA SHISCHES          AGENTE
129  919015013  73003562            DARIO DARWIN MAMANI JARA         CLIENTE
130  933710754  61296135       RIVERA GARRIDO JASURI JHANETH          AGENTE
131  931099399  75200837       AGUILAR MOLINA JOSEPH MICHAEL          AGENTE
132  954830302  73150537     PACHECO YUPANQUI TANIA MILAGROS         CLIENTE
133  937611520  74075275       JOAQUIN ANTONIO CALLE MENDOZA          AGENTE

     ... TIPIFICACIONES POR AGENTES  Unnamed: 27  Unnamed: 28  Unnamed: 29  \
102  ...                         NaN         NaN          NaN          NaN
103  ...                         NaN         NaN          NaN          NaN
104  ...                         NaN         NaN          NaN          NaN
105  ...                         NaN         NaN          NaN          NaN
106  ...                         NaN         NaN          NaN          NaN
107  ...                         NaN         NaN          NaN          NaN
108  ...                         NaN         NaN          NaN          NaN
109  ...                         NaN         NaN          NaN          NaN
110  ...                         NaN         NaN          NaN          NaN
111  ...                         NaN         NaN          NaN          NaN
112  ...                         NaN         NaN          NaN          NaN
113  ...                         NaN         NaN          NaN          NaN
114  ...                         NaN         NaN          NaN          NaN
115  ...                         NaN         NaN          NaN          NaN
116  ...                         NaN         NaN          NaN          NaN
117  ...                         NaN         NaN          NaN          NaN
118  ...                         NaN         NaN          NaN          NaN
119  ...                         NaN         NaN          NaN          NaN
120  ...                         NaN         NaN          NaN          NaN
121  ...                         NaN         NaN          NaN          NaN
122  ...                         NaN         NaN          NaN          NaN
123  ...                         NaN         NaN          NaN          NaN
124  ...                         NaN         NaN          NaN          NaN
125  ...                         NaN         NaN          NaN          NaN
126  ...                         NaN         NaN          NaN          NaN
127  ...                         NaN         NaN          NaN          NaN
128  ...                         NaN         NaN          NaN          NaN
129  ...                         NaN         NaN          NaN          NaN
130  ...                         NaN         NaN          NaN          NaN
131  ...                         NaN         NaN          NaN          NaN
132  ...                         NaN         NaN          NaN          NaN
133  ...                         NaN         NaN          NaN          NaN

     Unnamed: 30  Unnamed: 31 Unnamed: 32  Unnamed: 33  Unnamed: 34  \
102          NaN          NaN         NaN          NaN          NaN
103          NaN          NaN         NaN          NaN          NaN
104          NaN          NaN         NaN          NaN          NaN
105          NaN          NaN         NaN          NaN          NaN
106          NaN          NaN         NaN          NaN          NaN
107          NaN          NaN         NaN          NaN          NaN
108          NaN          NaN         NaN          NaN          NaN
109          NaN          NaN         NaN          NaN          NaN
110          NaN          NaN         NaN          NaN          NaN
111          NaN          NaN         NaN          NaN          NaN
112          NaN          NaN         NaN          NaN          NaN
113          NaN          NaN         NaN          NaN          NaN
114          NaN          NaN         NaN          NaN          NaN
115          NaN          NaN         NaN          NaN          NaN
116          NaN          NaN         NaN          NaN          NaN
117          NaN          NaN         NaN          NaN          NaN
118          NaN          NaN         NaN          NaN          NaN
119          NaN          NaN         NaN          NaN          NaN
120          NaN          NaN         NaN          NaN          NaN
121          NaN          NaN         NaN          NaN          NaN
122          NaN          NaN         NaN          NaN          NaN
123          NaN          NaN         NaN          NaN          NaN
124          NaN          NaN         NaN          NaN          NaN
125          NaN          NaN         NaN          NaN          NaN
126          NaN          NaN         NaN          NaN          NaN
127          NaN          NaN         NaN          NaN          NaN
128          NaN          NaN         NaN          NaN          NaN
129          NaN          NaN         NaN          NaN          NaN
130          NaN          NaN         NaN          NaN          NaN
131          NaN          NaN         NaN          NaN          NaN
132          NaN          NaN         NaN          NaN          NaN
133          NaN          NaN         NaN          NaN          NaN

     Unnamed: 35
102          NaN
103          NaN
104          NaN
105          NaN
106          NaN
107          NaN
108          NaN
109          NaN
110          NaN
111          NaN
112          NaN
113          NaN
114          NaN
115          NaN
116          NaN
117          NaN
118          NaN
119          NaN
120          NaN
121          NaN
122          NaN
123          NaN
124          NaN
125          NaN
126          NaN
127          NaN
128          NaN
129          NaN
130          NaN
131          NaN
132          NaN
133          NaN

[32 rows x 36 columns]>

In [ ]:
df[(df['LIST_ID'] >= 250) & (df['STATUS'] == '1CEF01')]

LIST_ID                        31
CAMPAÑA                        31
FECHA                          31
TMO                            31
STATUS                         31
TIPIFICACION                   31
TELEFONO                       31
DNI                            31
AGENTE                         31
TERMINO_LLAMADA                31
TIPO_LLAMADA                   31
GESTION                        31
AGENDADO                       31
VENTA                          31
VOLVER A LLAMAR                31
CORTA LLAMADA                  31
TIPOLOGÌA                      31
Unnamed: 17                     0
Unnamed: 18                     0
Unnamed: 19                     0
% De TIPIFICACION               0
Unnamed: 21                     0
Unnamed: 22                     0
Unnamed: 23                     0
Unnamed: 24                     0
Unnamed: 25                     0
TIPIFICACIONES POR AGENTES      0
Unnamed: 27                     0
Unnamed: 28                     0
Unnamed: 29                     0
Unnamed: 30                     0
Unnamed: 31                     0
Unnamed: 32                     0
Unnamed: 33                     0
Unnamed: 34                     0
Unnamed: 35                     0
dtype: int64

In [71]:
df

,LIST_ID,CAMPAÑA,FECHA,TMO,STATUS,TIPIFICACION,TELEFONO,DNI,AGENTE,TERMINO_LLAMADA,...,TIPIFICACIONES POR AGENTES,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35
0,396,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,914922217,74536535,SANDRA PAMELA CONDEZO SOTO,ABANDON,...,TIPOLOGÌA,Sospechosa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,278,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,937647656,74075275,JOAQUIN ANTONIO CALLE MENDOZA,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,396,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,992625371,10015709,YSABELINA LOA RAMOS,NONE,...,Cuenta de FECHA,Etiquetas de columna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,396,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,950173921,74417924,ANGEL LEONEL GUIDINO HERRERA,AGENTE,...,Etiquetas de fila,AUTORIZA - AGENDADO,AUTORIZA - VENTA,AUTORIZA- CONF CON SU OPERADOR,AUTORIZA- CORTA LLAMADA,FUERA DE SERVICIO,LLAMADA MUDA,NO AUTORIZA COMUNICACION,NO CONTESTA,Total general
4,404,WINOUT,2025-10-01,00:00:00,1CEF05,AUTORIZA- NO DESEA-PRODUCTO,933024736,72322895,DEYANIRA AYLIN ESPINOZA CHECA,AGENTE,...,AGUILAR MOLINA JOSEPH MICHAEL,20,4,NaN,6,NaN,NaN,335,1,366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7829,408,WINOUT,2025-10-01,NaN,INCALL,NaN,968092940,60683672,CIELO DEL PILAR PANDURO FLORES,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7830,408,WINOUT,2025-10-01,NaN,INCALL,NaN,953693430,76602643,CIOMARA FLOR VILLANO MOLLE,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7831,998,WINOUT,2025-10-01,NaN,INCALL,NaN,994037592,73150537,PACHECO YUPANQUI TANIA MILAGROS,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7832,408,WINOUT,2025-10-01,NaN,INCALL,NaN,998481147,74802241,ALEXSANDRA VICTORIA CHINCHON RAZON,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7833,372,WINOUT,2025-10-01,NaN,INCALL,NaN,971487827,73285107,JEAN PAUL SALAMANCA TORRES,NONE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
df.iloc[0:21,0:9]

,LIST_ID,CAMPAÑA,FECHA,TMO,STATUS,TIPIFICACION,TELEFONO,DNI,AGENTE
0,396,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,914922217,74536535,SANDRA PAMELA CONDEZO SOTO
1,278,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,937647656,74075275,JOAQUIN ANTONIO CALLE MENDOZA
2,396,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,992625371,10015709,YSABELINA LOA RAMOS
3,396,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,950173921,74417924,ANGEL LEONEL GUIDINO HERRERA
4,404,WINOUT,2025-10-01,00:00:00,1CEF05,AUTORIZA- NO DESEA-PRODUCTO,933024736,72322895,DEYANIRA AYLIN ESPINOZA CHECA
5,404,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,959159110,70856388,CHRISTIAN ANDERSON GARCIA VILCA
6,393,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,989519562,70125736,MABEL YESSENIA DUENAS TOMAS
7,404,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,914666270,70856388,CHRISTIAN ANDERSON GARCIA VILCA
8,998,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,908840517,70125736,MABEL YESSENIA DUENAS TOMAS
9,998,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,908840517,70125736,MABEL YESSENIA DUENAS TOMAS
10,404,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,992580806,46691128,HAUDE DAVID CALDERON SAN MIGUEL
11,998,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,949432747,75663085,ALEXIS ARTURO SILVA RUIZ
12,504,WINOUT,2025-10-01,00:00:00,3NCO03,CASILLA DE VOZ,988000723,46691128,HAUDE DAVID CALDERON SAN MIGUEL
13,404,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,968230838,73285107,JEAN PAUL SALAMANCA TORRES
14,404,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,968230838,73285107,JEAN PAUL SALAMANCA TORRES
15,404,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,960370449,73003562,DARIO DARWIN MAMANI JARA
16,404,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,941891116,74973677,JEYSON PAUL ESPINOZA DIAZ
17,998,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,983605813,10015709,YSABELINA LOA RAMOS
18,278,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,937647656,74075275,JOAQUIN ANTONIO CALLE MENDOZA
19,503,WINOUT,2025-10-01,00:00:00,3NCO01,NO CONTESTA,900217807,3411835,EDURYELIS NOHEMI SANTAMARA NOGUERA
20,998,WINOUT,2025-10-01,00:00:00,2CNE01,AUTORIZA- CORTA LLAMADA,931655878,74417924,ANGEL LEONEL GUIDINO HERRERA

In [76]:
df[(df['TIPIFICACION'] == 'AUTORIZA - AGENDADO') & (df['LIST_ID']== 998)]

,LIST_ID,CAMPAÑA,FECHA,TMO,STATUS,TIPIFICACION,TELEFONO,DNI,AGENTE,TERMINO_LLAMADA,...,TIPIFICACIONES POR AGENTES,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35
11,998,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,949432747,75663085,ALEXIS ARTURO SILVA RUIZ,AGENTE,...,CIOMARA FLOR VILLANO MOLLE,NaN,NaN,7,216,NaN,8,NaN,1,232
35,998,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,989155138,75663085,ALEXIS ARTURO SILVA RUIZ,AGENTE,...,YOHEMILIS MARGIOLIS GONZALEZ MOYETONES,14,NaN,NaN,207,NaN,NaN,1,4,226
38,998,WINOUT,2025-10-01,00:00:00,1CEF02,AUTORIZA - AGENDADO,978957721,75663085,ALEXIS ARTURO SILVA RUIZ,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,998,WINOUT,2025-10-01,00:00:02,1CEF02,AUTORIZA - AGENDADO,9005653529am,70494580,NICOLE GERALDINE YGUIA ARANCIBIA,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1523,998,WINOUT,2025-10-01,00:00:14,1CEF02,AUTORIZA - AGENDADO,930792763,75663085,ALEXIS ARTURO SILVA RUIZ,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1723,998,WINOUT,2025-10-01,00:00:15,1CEF02,AUTORIZA - AGENDADO,949432747,75663085,ALEXIS ARTURO SILVA RUIZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1823,998,WINOUT,2025-10-01,00:00:16,1CEF02,AUTORIZA - AGENDADO,9005653529am,70494580,NICOLE GERALDINE YGUIA ARANCIBIA,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2223,998,WINOUT,2025-10-01,00:00:18,1CEF02,AUTORIZA - AGENDADO,989155138,75663085,ALEXIS ARTURO SILVA RUIZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2570,998,WINOUT,2025-10-01,00:00:20,1CEF02,AUTORIZA - AGENDADO,989155138,75663085,ALEXIS ARTURO SILVA RUIZ,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3868,998,WINOUT,2025-10-01,00:00:28,1CEF02,AUTORIZA - AGENDADO,999001567,8338310,YOHEMILIS MARGIOLIS GONZALEZ MOYETONES,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3961,998,WINOUT,2025-10-01,00:00:29,1CEF02,AUTORIZA - AGENDADO,930792763,75663085,ALEXIS ARTURO SILVA RUIZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4419,998,WINOUT,2025-10-01,00:00:32,1CEF02,AUTORIZA - AGENDADO,989155138,75663085,ALEXIS ARTURO SILVA RUIZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4987,998,WINOUT,2025-10-01,00:00:38,1CEF02,AUTORIZA - AGENDADO,930792763,75663085,ALEXIS ARTURO SILVA RUIZ,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5101,998,WINOUT,2025-10-01,00:00:39,1CEF02,AUTORIZA - AGENDADO,994037592,73150537,PACHECO YUPANQUI TANIA MILAGROS,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5110,998,WINOUT,2025-10-01,00:00:39,1CEF02,AUTORIZA - AGENDADO,930792763,75663085,ALEXIS ARTURO SILVA RUIZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5178,998,WINOUT,2025-10-01,00:00:40,1CEF02,AUTORIZA - AGENDADO,991553808,74858894,YESSENIA MILAGROS PULACHE ZUTA,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5419,998,WINOUT,2025-10-01,00:00:43,1CEF02,AUTORIZA - AGENDADO,930792763,75663085,ALEXIS ARTURO SILVA RUIZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5623,998,WINOUT,2025-10-01,00:00:45,1CEF02,AUTORIZA - AGENDADO,949432747,75663085,ALEXIS ARTURO SILVA RUIZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6200,998,WINOUT,2025-10-01,00:00:55,1CEF02,AUTORIZA - AGENDADO,930792763,75663085,ALEXIS ARTURO SILVA RUIZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,998,WINOUT,2025-10-01,00:02:34,1CEF02,AUTORIZA - AGENDADO,963713546,1166457,VICTOR HUGO DEL AGUILA RAMIREZ,CLIENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7653,998,WINOUT,2025-10-01,00:04:03,1CEF02,AUTORIZA - AGENDADO,978957721,75663085,ALEXIS ARTURO SILVA RUIZ,AGENTE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
df['TMO'].mean

<bound method Series.mean of 0       00:00:00
1       00:00:00
2       00:00:00
3       00:00:00
4       00:00:00
          ...
7829         NaN
7830         NaN
7831         NaN
7832         NaN
7833         NaN
Name: TMO, Length: 7834, dtype: object>